services:
  # Database service
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - mynetwork

  # Redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # PHP service
  app:
    build: .
    ports:
      - "5000"
    volumes:
      - .:/var/www/html
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
